version: '3.3'

services:
    python:
        container_name: python
        image: python:latest
        volumes:
            - ./:/var/www/html
        tty: true
    ruby:
        container_name: ruby
        image: ruby:latest
        volumes:
            - ./:/var/www/html
        tty: true
    node:
        container_name: node
        image: node:latest
        ports:
            - 8000:8000
        volumes:
            - ./:/var/www/html
        tty: true